services:
  - type: web
    name: nfl-trivia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 2 --bind 0.0.0.0:$PORT --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nfl-trivia-db
          property: connectionString

databases:
  - name: nfl-trivia-db
    plan: free